### ISSUE TITLE
Hue Tap

### ISSUE THREAD

**Issue by akafester** [martinezmp3/deCONZ#1]
Hi

I just connected 2 Hue Tap's to Deconz without issue. 
The child driver is created as expected, and the pushes are registered in Hubitat. 
But Hubitat is reporting 0 buttons, so I can't do anything.

Is there something I'm missing?

**Comment by martinezmp3** [comment]
Press the button on the hue tap and observe the logs it should increase the number of button if not post the logs here and will take a look

**Comment by akafester** [comment]
The number of buttons doesn't change. All I can see in the logs is that button 0 (zero) changes action

The logs: 
`dev:1082020-10-12 16:27:00.487 debugLast Update:2020-10-12T16:26:58.487
dev:1062020-10-12 16:27:00.482 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:27:00.475 debugbutton = 0 action = 16
dev:1062020-10-12 16:27:00.468 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:26:58.487], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:27:00.463 debugparse call
dev:1082020-10-12 16:26:59.630 debugLast Update:2020-10-12T16:26:57.646
dev:1062020-10-12 16:26:59.625 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:26:59.619 debugbutton = 0 action = 17
dev:1062020-10-12 16:26:59.610 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:17, lastupdated:2020-10-12T16:26:57.646], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:26:59.605 debugparse call
dev:1082020-10-12 16:26:58.522 debugLast Update:2020-10-12T16:26:56.503
dev:1062020-10-12 16:26:58.517 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:26:58.509 debugbutton = 0 action = 34
dev:1062020-10-12 16:26:58.500 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:26:56.503], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:26:58.492 debugparse call
dev:1072020-10-12 16:26:57.759 debugLast Update:2020-10-12T16:26:55.737
dev:1062020-10-12 16:26:57.753 debugUpdate for Stue - Tap
dev:1072020-10-12 16:26:57.744 debugbutton = 0 action = 34
dev:1062020-10-12 16:26:57.736 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:26:55.737], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:26:57.728 debugparse call
dev:1072020-10-12 16:26:57.193 debugLast Update:2020-10-12T16:26:55.168
dev:1062020-10-12 16:26:57.188 debugUpdate for Stue - Tap
dev:1072020-10-12 16:26:57.179 debugbutton = 0 action = 34
dev:1062020-10-12 16:26:57.172 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:26:55.168], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:26:57.163 debugparse call
dev:1072020-10-12 16:26:56.227 debugLast Update:2020-10-12T16:26:54.209
dev:1062020-10-12 16:26:56.223 debugUpdate for Stue - Tap
dev:1072020-10-12 16:26:56.214 debugbutton = 0 action = 16
dev:1062020-10-12 16:26:56.206 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:26:54.209], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:26:56.201 debugparse call
dev:1072020-10-12 16:26:54.135 debugLast Update:2020-10-12T16:26:52.122
dev:1062020-10-12 16:26:54.130 debugUpdate for Stue - Tap
dev:1072020-10-12 16:26:54.122 debugbutton = 0 action = 17
dev:1062020-10-12 16:26:54.114 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:17, lastupdated:2020-10-12T16:26:52.122], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:26:54.109 debugparse call
dev:1062020-10-12 16:26:53.067 debugrecive: [attr:[id:1, lastseen:2020-10-12T16:26Z, manufacturername:dresden elektronik, modelid:RaspBee II, name:Configuration tool 1, type:Configuration tool, uniqueid:00:21:2e:ff:ff:06:1b:31-01], e:changed, id:1, r:lights, t:event, uniqueid:00:21:2e:ff:ff:06:1b:31-01]
dev:1062020-10-12 16:26:53.057 debugparse call
dev:1072020-10-12 16:26:52.582 debugLast Update:2020-10-12T16:26:50.566
dev:1062020-10-12 16:26:52.577 debugUpdate for Stue - Tap
dev:1072020-10-12 16:26:52.569 debugbutton = 0 action = 16
dev:1062020-10-12 16:26:52.562 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:26:50.566], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:26:52.557 debugparse call
dev:1072020-10-12 16:26:51.407 debugLast Update:2020-10-12T16:26:49.386
dev:1062020-10-12 16:26:51.402 debugUpdate for Stue - Tap
dev:1072020-10-12 16:26:51.393 debugbutton = 0 action = 34
dev:1062020-10-12 16:26:51.384 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:26:49.386], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:26:51.376 debugparse call
dev:1072020-10-12 16:26:27.205 debugLast Update:2020-10-12T16:26:25.229
dev:1062020-10-12 16:26:27.201 debugUpdate for Stue - Tap
dev:1072020-10-12 16:26:27.194 debugbutton = 0 action = 34
dev:1062020-10-12 16:26:27.188 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:26:25.229], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:26:27.184 debugparse call
dev:1082020-10-12 16:26:27.157 debugLast Update:2020-10-12T16:26:25.135
dev:1062020-10-12 16:26:27.152 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:26:27.139 debugbutton = 0 action = 34
dev:1062020-10-12 16:26:27.130 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:26:25.135], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:26:27.124 debugparse call
dev:1062020-10-12 16:25:50.670 debugrecive: [attr:[id:1, lastseen:2020-10-12T16:25Z, manufacturername:dresden elektronik, modelid:RaspBee II, name:Configuration tool 1, type:Configuration tool, uniqueid:00:21:2e:ff:ff:06:1b:31-01], e:changed, id:1, r:lights, t:event, uniqueid:00:21:2e:ff:ff:06:1b:31-01]
dev:1062020-10-12 16:25:50.657 debugparse call
dev:1062020-10-12 16:25:50.356 debugrecive: [e:changed, id:1, r:sensors, state:[dark:true, daylight:false, lastupdated:2020-10-12T16:25:48.364, status:200, sunrise:2020-10-12T05:35:43, sunset:2020-10-12T16:18:36], t:event, uniqueid:00:21:2e:ff:ff:06:1b:31-01]
dev:1062020-10-12 16:25:50.350 debugparse call
dev:1062020-10-12 16:24:48.285 debugrecive: [attr:[id:1, lastseen:2020-10-12T16:24Z, manufacturername:dresden elektronik, modelid:RaspBee II, name:Configuration tool 1, type:Configuration tool, uniqueid:00:21:2e:ff:ff:06:1b:31-01], e:changed, id:1, r:lights, t:event, uniqueid:00:21:2e:ff:ff:06:1b:31-01]
dev:1062020-10-12 16:24:48.278 debugparse call
dev:1072020-10-12 16:24:26.539 debugLast Update:2020-10-12T16:24:24.549
dev:1062020-10-12 16:24:26.523 debugUpdate for Stue - Tap
dev:1072020-10-12 16:24:26.516 debugbutton = 0 action = 17
dev:1062020-10-12 16:24:26.509 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:17, lastupdated:2020-10-12T16:24:24.549], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:24:26.505 debugparse call
dev:1082020-10-12 16:24:26.010 debugLast Update:2020-10-12T16:24:23.993
dev:1062020-10-12 16:24:26.005 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:24:25.998 debugbutton = 0 action = 17
dev:1062020-10-12 16:24:25.990 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:17, lastupdated:2020-10-12T16:24:23.993], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:24:25.985 debugparse call
dev:1082020-10-12 16:24:25.302 debugLast Update:2020-10-12T16:24:23.279
dev:1062020-10-12 16:24:25.297 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:24:25.290 debugbutton = 0 action = 18
dev:1062020-10-12 16:24:25.281 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:24:23.279], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:24:25.272 debugparse call
dev:1082020-10-12 16:24:24.541 debugLast Update:2020-10-12T16:24:22.525
dev:1062020-10-12 16:24:24.536 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:24:24.528 debugbutton = 0 action = 16
dev:1062020-10-12 16:24:24.521 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:24:22.525], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:24:24.513 debugparse call
dev:1082020-10-12 16:24:22.983 debugLast Update:2020-10-12T16:24:20.976
dev:1062020-10-12 16:24:22.978 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:24:22.971 debugbutton = 0 action = 34
dev:1062020-10-12 16:24:22.963 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:24:20.976], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:24:22.958 debugparse call
dev:1072020-10-12 16:24:21.938 debugLast Update:2020-10-12T16:24:19.947
dev:1062020-10-12 16:24:21.932 debugUpdate for Stue - Tap
dev:1072020-10-12 16:24:21.921 debugbutton = 0 action = 34
dev:1062020-10-12 16:24:21.911 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:24:19.947], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:24:21.905 debugparse call
dev:1062020-10-12 16:24:05.019 debugrecive: [e:changed, id:3, name:Soveværelse - Tap, r:sensors, t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:24:05.010 debugparse call
dev:1062020-10-12 16:23:52.849 debugrecive: [e:changed, id:3, name:Tap, r:sensors, t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:23:52.843 debugparse call
dev:1082020-10-12 16:23:51.868 debugLast Update:2020-10-12T16:23:49.849
dev:1062020-10-12 16:23:51.863 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:23:51.855 debugbutton = 0 action = 224
dev:1062020-10-12 16:23:51.847 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:224, lastupdated:2020-10-12T16:23:49.849], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:23:51.838 debugparse call
dev:1062020-10-12 16:23:45.890 debugrecive: [attr:[id:1, lastseen:2020-10-12T16:23Z, manufacturername:dresden elektronik, modelid:RaspBee II, name:Configuration tool 1, type:Configuration tool, uniqueid:00:21:2e:ff:ff:06:1b:31-01], e:changed, id:1, r:lights, t:event, uniqueid:00:21:2e:ff:ff:06:1b:31-01]
dev:1062020-10-12 16:23:45.883 debugparse call
dev:1072020-10-12 16:23:27.568 debugLast Update:2020-10-12T16:23:25.563
dev:1062020-10-12 16:23:27.564 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:27.555 debugbutton = 0 action = 18
dev:1062020-10-12 16:23:27.548 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:23:25.563], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:27.542 debugparse call
dev:1072020-10-12 16:23:26.960 debugLast Update:2020-10-12T16:23:24.942
dev:1062020-10-12 16:23:26.955 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:26.947 debugbutton = 0 action = 16
dev:1062020-10-12 16:23:26.939 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:23:24.942], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:26.933 debugparse call
dev:1072020-10-12 16:23:26.032 debugLast Update:2020-10-12T16:23:24.044
dev:1062020-10-12 16:23:26.027 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:26.017 debugbutton = 0 action = 17
dev:1062020-10-12 16:23:26.010 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:17, lastupdated:2020-10-12T16:23:24.044], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:26.002 debugparse call
dev:1072020-10-12 16:23:25.208 debugLast Update:2020-10-12T16:23:23.193
dev:1062020-10-12 16:23:25.203 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:25.195 debugbutton = 0 action = 34
dev:1062020-10-12 16:23:25.187 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:23:23.193], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:25.181 debugparse call
dev:1072020-10-12 16:23:24.576 debugLast Update:2020-10-12T16:23:22.570
dev:1062020-10-12 16:23:24.571 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:24.563 debugbutton = 0 action = 18
dev:1062020-10-12 16:23:24.557 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:23:22.570], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:24.553 debugparse call
dev:1072020-10-12 16:23:23.921 debugLast Update:2020-10-12T16:23:21.938
dev:1062020-10-12 16:23:23.917 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:23.909 debugbutton = 0 action = 16
dev:1062020-10-12 16:23:23.902 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:23:21.938], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:23.896 debugparse call
dev:1072020-10-12 16:23:23.109 debugLast Update:2020-10-12T16:23:21.126
dev:1062020-10-12 16:23:23.104 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:23.097 debugbutton = 0 action = 17
dev:1062020-10-12 16:23:23.089 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:17, lastupdated:2020-10-12T16:23:21.126], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:23.084 debugparse call
dev:1072020-10-12 16:23:22.393 debugLast Update:2020-10-12T16:23:20.413
dev:1062020-10-12 16:23:22.388 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:22.380 debugbutton = 0 action = 16
dev:1062020-10-12 16:23:22.373 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:23:20.413], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:22.369 debugparse call
dev:1072020-10-12 16:23:21.685 debugLast Update:2020-10-12T16:23:19.666
dev:1062020-10-12 16:23:21.680 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:21.671 debugbutton = 0 action = 18
dev:1062020-10-12 16:23:21.664 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:23:19.666], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:21.656 debugparse call
dev:1072020-10-12 16:23:20.724 debugLast Update:2020-10-12T16:23:18.741
dev:1062020-10-12 16:23:20.719 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:20.712 debugbutton = 0 action = 34
dev:1062020-10-12 16:23:20.704 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:23:18.741], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:20.699 debugparse call
dev:1072020-10-12 16:23:19.212 debugLast Update:2020-10-12T16:23:17.201
dev:1062020-10-12 16:23:19.208 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:19.199 debugbutton = 0 action = 18
dev:1062020-10-12 16:23:19.191 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:23:17.201], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:19.186 debugparse call
dev:1072020-10-12 16:23:17.667 debugLast Update:2020-10-12T16:23:15.652
dev:1062020-10-12 16:23:17.661 debugUpdate for Stue - Tap
dev:1072020-10-12 16:23:17.657 debugbutton = 0 action = 16
dev:1062020-10-12 16:23:17.651 debugrecive: [e:changed, id:2, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:23:15.652], t:event, uniqueid:00:00:00:00:00:44:88:76-f2]
dev:1062020-10-12 16:23:17.644 debugparse call
dev:1062020-10-12 16:22:45.884 debugrecive: [attr:[id:1, lastseen:2020-10-12T16:22Z, manufacturername:dresden elektronik, modelid:RaspBee II, name:Configuration tool 1, type:Configuration tool, uniqueid:00:21:2e:ff:ff:06:1b:31-01], e:changed, id:1, r:lights, t:event, uniqueid:00:21:2e:ff:ff:06:1b:31-01]
dev:1062020-10-12 16:22:45.877 debugparse call
dev:1082020-10-12 16:22:32.411 debugLast Update:2020-10-12T16:22:30.406
dev:1062020-10-12 16:22:32.406 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:32.399 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:32.392 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:30.406], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:32.386 debugparse call
dev:1082020-10-12 16:22:31.652 debugLast Update:2020-10-12T16:22:29.637
dev:1062020-10-12 16:22:31.647 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:31.640 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:31.633 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:29.637], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:31.627 debugparse call
dev:1082020-10-12 16:22:31.022 debugLast Update:2020-10-12T16:22:29.011
dev:1062020-10-12 16:22:31.018 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:31.011 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:31.004 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:29.011], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:30.998 debugparse call
dev:1082020-10-12 16:22:30.463 debugLast Update:2020-10-12T16:22:28.445
dev:1062020-10-12 16:22:30.458 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:30.450 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:30.443 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:28.445], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:30.436 debugparse call
dev:1082020-10-12 16:22:29.956 debugLast Update:2020-10-12T16:22:27.937
dev:1062020-10-12 16:22:29.950 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:29.942 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:29.935 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:27.937], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:29.927 debugparse call
dev:1082020-10-12 16:22:29.434 debugLast Update:2020-10-12T16:22:27.433
dev:1062020-10-12 16:22:29.429 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:29.422 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:29.413 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:27.433], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:29.408 debugparse call
dev:1082020-10-12 16:22:28.874 debugLast Update:2020-10-12T16:22:26.866
dev:1062020-10-12 16:22:28.869 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:28.862 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:28.855 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:26.866], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:28.849 debugparse call
dev:1082020-10-12 16:22:28.287 debugLast Update:2020-10-12T16:22:26.281
dev:1062020-10-12 16:22:28.267 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:28.261 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:28.254 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:26.281], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:28.238 debugparse call
dev:1082020-10-12 16:22:27.789 debugLast Update:2020-10-12T16:22:25.770
dev:1062020-10-12 16:22:27.783 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:27.776 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:27.768 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:25.770], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:27.761 debugparse call
dev:1082020-10-12 16:22:27.242 debugLast Update:2020-10-12T16:22:25.221
dev:1062020-10-12 16:22:27.236 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:27.229 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:27.222 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:25.221], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:27.213 debugparse call
dev:1082020-10-12 16:22:26.563 debugLast Update:2020-10-12T16:22:24.572
dev:1062020-10-12 16:22:26.556 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:26.547 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:26.537 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:24.572], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:26.530 debugparse call
dev:1082020-10-12 16:22:26.005 debugLast Update:2020-10-12T16:22:24.019
dev:1062020-10-12 16:22:26.000 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:25.992 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:25.985 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:24.019], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:25.978 debugparse call
dev:1082020-10-12 16:22:25.233 debugLast Update:2020-10-12T16:22:23.255
dev:1062020-10-12 16:22:25.228 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:25.225 debugbutton = 0 action = 18
dev:1062020-10-12 16:22:25.222 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:18, lastupdated:2020-10-12T16:22:23.255], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:25.215 debugparse call
dev:1082020-10-12 16:22:24.456 debugLast Update:2020-10-12T16:22:22.476
dev:1062020-10-12 16:22:24.447 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:24.441 debugbutton = 0 action = 17
dev:1062020-10-12 16:22:24.435 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:17, lastupdated:2020-10-12T16:22:22.476], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:24.431 debugparse call
dev:1082020-10-12 16:22:23.276 debugLast Update:2020-10-12T16:22:21.292
dev:1062020-10-12 16:22:23.270 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:23.263 debugbutton = 0 action = 16
dev:1062020-10-12 16:22:23.256 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:16, lastupdated:2020-10-12T16:22:21.292], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:23.247 debugparse call
dev:1082020-10-12 16:22:22.125 debugLast Update:2020-10-12T16:22:20.090
dev:1062020-10-12 16:22:22.122 debugUpdate for Soveværelse - Tap
dev:1082020-10-12 16:22:22.119 debugbutton = 0 action = 34
dev:1062020-10-12 16:22:22.116 debugrecive: [e:changed, id:3, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:22:20.090], t:event, uniqueid:00:00:00:00:00:44:8c:96-f2]
dev:1062020-10-12 16:22:22.101 debugparse call`

**Comment by akafester** [comment]
Button 1: action = 34
Button 2: action = 16
Button 3: action = 17
Button 4: action = 18

All buttons reported as button 0 but with those actions following.

**Comment by martinezmp3** [comment]
The api reporting do you events in a weird form I could fix it but I need each button report when you press it, hold it, release it and double press it I don’t know if that particular device has all the capabilities are only a few, if you give me the information I could modify the driver when I get home today.
every time you do an action on the button (press,hold,release,double tap) a line like this will show up: 
recive: [e:changed, id:3, r:sensors, state:[buttonevent:34, lastupdated:2020-10-12T16:22:20.090]
send the line with the corresponding action I get it going after work today

**Comment by akafester** [comment]
Copying from above: 

Press:
Button 1: action = 34
Button 2: action = 16
Button 3: action = 17
Button 4: action = 18

Double press is not a separate action, but I guess it could be simulated by monitoring for the same action within ~1 second or something. Personally, I don't care for the double press as that can be achieved in some other form in Rule Machine. 

Long press (hold) is not supported either. Can't see a way to reliably register that. :) 

Release is not supported either. It's supported on the Hue bridge somehow through a labs setting. But Deconz isn't reporting anything other than the press.

I think I have another issue, but I will open a separate one once I figure out what's happening reliably.

Thank you for your time on this. It's really appreciated. 

Edit: Release info and some other stuff

**Comment by martinezmp3** [comment]
can you put on a browser from a computer on your lan this url: http://"your_deCONZ_hub_IP"/api/"api_key"/sensors/"hue_Tap_ID"
change the quote with your device information you could get use the same api key that your hubitat use get it from the setting page on tha parent device
the hue_tap_id you could get it from the logs look like you have 2 different taps (ID1,ID2) or you remove and add the same one the result post it back i have to get more information if the device to fix the driver.

**Comment by martinezmp3** [comment]
I think I got what I need to adjust the driver to the hue tap please update your parent and button driver, delete the current tap device previously created on the hubitat hub and press any button on the tap to generate the a new device with the correct driver apparently the tap only send push event.
Please post back results to close the issue.
thanks

**Comment by akafester** [comment]
I've tried the new drivers and it seems to run as expected. I'm closing this, and thank you very much for the swift fix :).
